-- NyayaFlow AI Database Schema Definition
-- Optimized for PostgreSQL / Supabase Sovereign Deployments

-- Enable UUID extension if supported
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS & ACCOUNT ROLES
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('citizen', 'advocate', 'police', 'registrar', 'judge', 'admin')),
    phone VARCHAR(30) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. ADVOCATE SPECIALIZED PROFILES
CREATE TABLE IF NOT EXISTS advocate_profiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    bar_council_no VARCHAR(100) UNIQUE NOT NULL,
    specialization VARCHAR(255) NOT NULL,
    experience_years INTEGER NOT NULL DEFAULT 0,
    languages VARCHAR(255),
    fee_estimate VARCHAR(100),
    availability VARCHAR(100) DEFAULT 'Available',
    rating DECIMAL(3, 2) DEFAULT 5.0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. PETITION COMPLAINTS INDEX
CREATE TABLE IF NOT EXISTS petitions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    citizen_id UUID REFERENCES users(id),
    advocate_id UUID REFERENCES users(id) NULL,
    category VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    language VARCHAR(50) NOT NULL DEFAULT 'English',
    suggested_court VARCHAR(255),
    ai_confidence VARCHAR(10) DEFAULT '0%',
    status VARCHAR(50) NOT NULL DEFAULT 'Scrutiny Pending' 
        CHECK (status IN ('Scrutiny Pending', 'Registry Audited', 'CNR Issued', 'Hearings Active', 'Disposed', 'Returned')),
    cnr_number VARCHAR(100) UNIQUE NULL, -- Set by Registrar, NEVER generated by AI
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. PHYSICAL FILES ARCHIVAL LOCATIONS
CREATE TABLE IF NOT EXISTS physical_archive_locations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    petition_id UUID REFERENCES petitions(id) ON DELETE CASCADE UNIQUE,
    building VARCHAR(255) NOT NULL,
    floor VARCHAR(100) NOT NULL,
    room_number VARCHAR(100) NOT NULL,
    rack_number VARCHAR(100) NOT NULL,
    cupboard_number VARCHAR(100),
    shelf_number VARCHAR(100) NOT NULL,
    box_number VARCHAR(100) NOT NULL,
    file_barcode VARCHAR(255) UNIQUE NOT NULL,
    logged_by UUID REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. CASE DOCUMENTS FILES
CREATE TABLE IF NOT EXISTS documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    petition_id UUID REFERENCES petitions(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(512) NOT NULL,
    file_type VARCHAR(100) NOT NULL,
    ocr_text TEXT,
    health_score INTEGER DEFAULT 0,
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. COURT CAUSE LIST TIMELINES & BENCH ORDERS
CREATE TABLE IF NOT EXISTS court_orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    petition_id UUID REFERENCES petitions(id) ON DELETE CASCADE,
    judge_id UUID REFERENCES users(id),
    hearing_date TIMESTAMP WITH TIME ZONE NOT NULL,
    action_taken VARCHAR(100) NOT NULL, -- e.g., Passed Injunction, Adjourned, Disposed
    order_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. PLATFORM SYSTEM AUDIT LOGS
CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) NULL,
    action VARCHAR(512) NOT NULL,
    ip_address VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for search optimizations
CREATE INDEX IF NOT EXISTS idx_petitions_cnr ON petitions(cnr_number);
CREATE INDEX IF NOT EXISTS idx_petitions_status ON petitions(status);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_documents_petition ON documents(petition_id);
CREATE INDEX IF NOT EXISTS idx_archive_barcode ON physical_archive_locations(file_barcode);
